### ISSUE TITLE
sparrow3d missing rg350m support

### ISSUE THREAD

**Issue by dragonation** [od-contrib/opks#2]
While building the sd_image.bin for RG350M, it will report missing sparrow3d dependency

**Comment by dragonation** [comment]
```
rg350m@500196e6a387:/rg350m/buildroot$ make sparrow3d-dirclean
rm -Rf /rg350m/buildroot/output/build/sparrow3d-2033349d
rg350m@500196e6a387:/rg350m/buildroot$ make sparrow3d-rebuild
rm -f /rg350m/buildroot/output/build/sparrow3d-2033349d/.stamp_installed
rm -f /rg350m/buildroot/output/build/sparrow3d-2033349d/.stamp_staging_installed
rm -f /rg350m/buildroot/output/build/sparrow3d-2033349d/.stamp_target_installed
rm -f /rg350m/buildroot/output/build/sparrow3d-2033349d/.stamp_images_installed
rm -f /rg350m/buildroot/output/build/sparrow3d-2033349d/.stamp_host_installed
rm -f /rg350m/buildroot/output/build/sparrow3d-2033349d/.stamp_built
/bin/bash: /rg350m/buildroot/output/build/sparrow3d-2033349d/.files-list.after: No such file or directory
make: *** [package/pkg-generic.mk:359: /rg350m/buildroot/output/build/sparrow3d-2033349d/.stamp_installed] Error 1
```

The bugs remains stil. I tried to rebuild the sparrow3d package, but it report a strange error?

**Comment by glebm** [comment]
Is this from the latest commit?
Thought I fixed that

**Comment by glebm** [comment]
The latest commit is 0be43b0d3381f659da09e91c4cad0d044d373b31

**Comment by dragonation** [comment]
> The latest commit is [0be43b0](https://github.com/od-contrib/opks/commit/0be43b0d3381f659da09e91c4cad0d044d373b31)

YES, I found it. after renamed dependencies, the image is generated finally. 

Thanks

**Comment by dragonation** [comment]
```
# SPARROW3D_INSTALL_TARGET = NO
```

This line should be commented to make the image be generated successfully, otherwise the build of sparrow3d will be ignored.

**Comment by glebm** [comment]
We don't actually want to install sparrow3d, it is only ever linked statically

**Comment by dragonation** [comment]
> We don't actually want to install sparrow3d, it is only ever linked statically

I know, but the build is failed... Or, there is somewhere else to fix the failure

**Comment by glebm** [comment]
It succeeded for me, what command did you use to build?

**Comment by dragonation** [comment]
I am making a clear build, maybe some dirty modification caused the bug.

**Comment by dragonation** [comment]
Clean build is OK, no more bugs
